package com.lcl.galaxy.mybatis.xml.mapper;

import com.lcl.galaxy.mybatis.common.domain.UserTest1;

public interface UserTest1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test1
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test1
     *
     * @mbggenerated
     */
    int insert(UserTest1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test1
     *
     * @mbggenerated
     */
    int insertSelective(UserTest1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test1
     *
     * @mbggenerated
     */
    UserTest1 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test1
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserTest1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test1
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserTest1 record);
}