package com.lcl.galaxy.mybatis.xml.mapper;

import com.lcl.galaxy.mybatis.common.domain.UserTestDemo2;

public interface UserTestDemo2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test2
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test2
     *
     * @mbggenerated
     */
    int insert(UserTestDemo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test2
     *
     * @mbggenerated
     */
    int insertSelective(UserTestDemo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test2
     *
     * @mbggenerated
     */
    UserTestDemo2 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test2
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserTestDemo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_test2
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserTestDemo2 record);
}